name: 'Install pre-requisites'
description: 'Install pre-requisites for building paladin'

runs:
  using: 'composite'
  steps:
  - name: Install protoc
    shell: bash
    run: |
      PB_REL="https://github.com/protocolbuffers/protobuf/releases"
      curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
      unzip protoc-25.1-linux-x86_64.zip -d protoc
      echo "${PWD}/protoc/bin" >> $GITHUB_PATH

  # Set up Java
  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: 21

  # Set up Go
  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: '1.24'
      check-latest: true
      cache-dependency-path: |
        **/*.sum

  # Set up Gradle
  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v4
