apiVersion: v2
name: paladin-operator
description: A Helm chart for Kubernetes

type: application

# The chart version is overwritten at the release 
version: 0.7.1

# The app version is overwritten at the release 
appVersion: "0.0.0"
